# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4

      - name: Set up Go
        uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6
        with:
          go-version: '1.25.1'

      - name: Display the version of go that we have installed
        run: go version

      - name: Display the release tag
        run: echo ${{ github.event.release.tag_name }}

      - name: Install Dependencies
        run: go mod tidy

      - name: Build
        run: go build -v ./...

      - name: "DEBUG: What's our directory & what's in it?"
        run: pwd && ls

      - name: Build the sysinfo executables
        run: ./build-executables.sh ${{ github.event.release.tag_name }}

      - name: List the sysinfo executables
        run: ls -l ./release

      - name: Upload the sysinfo binaries
        uses: svenstaro/upload-release-action@81c65b7cd4de9b2570615ce3aad67a41de5b1a13 # v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: main
          file: ./release/sysinfo-*
          file_glob: true
          overwrite: true
